Lesson1
dalisov/javalisov pull request #3
Opened 2023-09-26 13:40 UTC by dalisov

2023-09-26 14:16 UTC, MVlasovD requested changes

2023-09-26 14:16 UTC, MVlasovD commented on src/Excercises/ex2_LargerOfTwoNumbers.java
> +public class ex2_LargerOfTwoNumbers {
название?

2023-09-26 14:52 UTC, dalisov commented
Поправил и добавил третью задачу

2023-09-26 15:04 UTC, MVlasovD requested changes

2023-09-26 15:04 UTC, MVlasovD commented on src/Exercises/NumbersInRange.java
> +        System.out.println();
какие-то наслоенные функции, а по итогу простые числа не выводит
много явных приведений к лонгу, зачем?
простые числа - посмотри что это

2023-09-27 08:27 UTC, MVlasovD requested changes

2023-09-27 08:27 UTC, MVlasovD commented on src/Exercises/PrimeNumbersInRange.java
> +        var y = scan.nextDouble();
это работает, но зачем работать c даблом, когда можно с интом

2023-09-27 08:27 UTC, MVlasovD commented on src/Exercises/LargestOfTwo.java
> +        var y = scan.nextDouble();
```suggestion
        var y = scan.nextInt();
```

2023-09-27 09:17 UTC, MVlasovD commented on src/Exercises/ShoppingCart.java
> +        String f = null;
название переменной совсем не очень

2023-09-27 09:20 UTC, MVlasovD commented on src/Exercises/ShoppingCart.java
> +
здесь пустая строка не нужна

2023-09-27 10:45 UTC, MVlasovD requested changes

2023-09-27 10:45 UTC, MVlasovD commented on src/Exercises/EnteringPassword.java
> +        while (!buff.equals(passwd)) {
зачем два цикла вайл

2023-09-27 11:47 UTC, MVlasovD approved these changes

2023-09-27 11:47 UTC, merged